name: CMake

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build-ubuntu:
        runs-on: [ubuntu-18.04]
        steps:
            - uses: actions/checkout@v2
            
            - name: Configure Environment
              run: |
                  sudo add-apt-repository -y ppa:jonathonf/gcc-9.2
                  sudo add-apt-repository -y ppa:hnakamur/libarchive
                  sudo add-apt-repository -y ppa:hnakamur/libzstd
                  sudo add-apt-repository -y ppa:hnakamur/cmake
                  sudo apt-get update
                  sudo apt-get install -qq gcc-9 cmake
                  
            - name: Create Build Environment
              run: cmake -E make_directory ${{runner.workspace}}/build

            - name: Configure CMake
              shell: bash
              working-directory: ${{runner.workspace}}/build
              run: CC=gcc-9 CXX=g++-9 cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release

            - name: Build
              working-directory: ${{runner.workspace}}/build
              shell: bash
              run: CC=gcc-9 CXX=g++-9 cmake --build . --config Release

            - name: Test
              working-directory: ${{runner.workspace}}/build
              shell: bash
              run: ctest -C Release
